name: Butane
on:
  push:
    branches: [ main ]
jobs:
  butane:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Ignition file
        run: docker run --interactive --rm quay.io/coreos/butane:release --pretty --strict < core.bu > core.ign
      - name: Upload Ignition file
        uses: actions/upload-artifact@v4
        with:
          name: core.ign
          path: core.ign
